### ISSUE TITLE
希望可以增加复制链接的功能

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [XZiar/Bilibili-Liver#1]
希望可以增加一个复制获取到的链接的键，这样可以更加简单的使用其他下载软件下载直播_(:3」∠)_

**Comment by XZiar** [comment]
妈呀居然有人看到这个项目了……
主要是不同浏览器对剪贴板的支持不一致，之前嫌引入clipboard.js太麻烦……
现在加入了

**Comment by Road-To-Gensokyo** [comment]
这么久才看到不好意思2333333非常感谢！！
